---
version: 2.1
jobs:
  unittests-python36:
    resource_class: small
    working_directory: ~/django-admin-fast-search
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements_test.txt
      - run:
          name: Run tests on Python 3.6
          command: tox -e py36-django-22,py36-django-30,py36-django-31,py36-django-32
  unittests-python37:
    resource_class: small
    working_directory: ~/django-admin-fast-search
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements_test.txt
      - run:
          name: Run tests on Python 3.7
          command: tox -e py37-django-22,py37-django-30,py37-django-31,py37-django-32
  unittests-python38:
    resource_class: small
    working_directory: ~/django-admin-fast-search
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements_test.txt
      - run:
          name: Run tests on Python 3.8
          command: tox -e py38-django-22,py38-django-30,py38-django-31,py38-django-32

  test_pypi_publish:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout  # checkout source code to working directory
      - run:
          name: Install dependencies
          command: pip install -r requirements_dev.txt -r requirements_test.txt
      - run:
          command: |  # create whl, install twine and publish to Test PyPI
            invoke test_release
  pypi_publish:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout  # checkout source code to working directory
      - run:
          name: Install dependencies
          command: pip install -r requirements_dev.txt -r requirements_test.txt
      - run:
          command: |  # create whl, install twine and publish to PyPI
            invoke testrelease

workflows:
  version: 2
  validate-pr:
    jobs:
      - unittests-python36
      - unittests-python37
      - unittests-python38
      - test_pypi_publish:
          context: Test-PyPi
      - pypi_publish:
          filters:
            branches:
              only:
                - main
