---
version: 2.1
jobs:
  unittests:
    resource_class: xlarge
    working_directory: ~/django-admin-fast-search
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements_test.txt
      - run:
          name: Run tests
          command: tox
workflows:
  version: 2
  validate-pr:
    jobs:
      - unittests
